name: Run main.py

on:
  # Run on push to the main branch
  push:
    branches: [ main ]
  # Additionally, run on schedule every 12 hours in IST (India Standard Time)
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 8 AM IST
    - cron: '01 20 * * 1-5'  # Runs every weekday at 8:01 PM IST
    - timezone: 'Asia/Kolkata'  # Specifies Indian Kolkata time zone for both schedules
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2  # Checkout the repository content

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # Install Python version 3.9

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install Python packages

      - run: python main.py
        env:
          SOME_SECRET: ${{ secrets.SOME_SECRET }}
          CITY: ${{ secrets.CITY }}  # Use environment variables if needed

      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)

      - uses: ad-m/github-push-action@v0.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
